server:
    port: 8080
security:
  oauth2:
    client:
      access-token-uri: http://localhost:8081/uaa/oauth/token
      user-authorization-uri: http://localhost:8081/uaa/oauth/authorize
      client-id: acme
      client-secret: acmesecret
      scope: write
    resource:
      token-info-uri: http://localhost:8081/uaa/oauth/check_token
      user-info-uri: http://localhost:8081/uaa/oauth/user